version: '3'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    platform: linux/arm64
    restart: always
    ports:
      - 80:8080
    environment:
      RUST_LOG: debug
      PORT: 8080
    links:
      - mariadb
    networks:
      - internal
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    networks:
      - internal
networks:
  internal:
    driver: bridge